### ISSUE TITLE
Performance Degradation on 0.10.0-preview2

### ISSUE THREAD

**Issue by worldbeater** [AvaloniaUI/AvaloniaEdit#104]
After upgrading a project which uses `AvaloniaEdit` from `0.9.0` to `0.10.0-preview2` things are working, well, 10 times slower. Using Ubuntu 18.04 LTS KDE, the following markup is used to instantiate and draw the editor:

```xaml
<avaloniaEdit:TextEditor
    FontFamily="Ubuntu Mono"
    x:Name="AvaloniaEdit"
    HorizontalAlignment="Stretch"
    VerticalAlignment="Stretch"
    HorizontalScrollBarVisibility="Auto"
    VerticalScrollBarVisibility="Auto">
    <avaloniaEdit:TextEditor.Options>
        <avaloniaEdit:TextEditorOptions 
            ConvertTabsToSpaces="True"
            IndentationSize="4"
            ShowTabs="True" />
    </avaloniaEdit:TextEditor.Options>
</avaloniaEdit:TextEditor>
``` 

This is how it was working with `0.9.*` (absolutely fast):

![ezgif-7-0c2fbeea4d6e](https://user-images.githubusercontent.com/6759207/88483707-55260d80-cf72-11ea-8054-67b7cfe1d8d1.gif)

This is how it works after the upgrade to `0.10.0-preview*` (almost a slideshow):

![ezgif-7-c95c19d00bb4](https://user-images.githubusercontent.com/6759207/88483715-61aa6600-cf72-11ea-93f7-4672ddbca563.gif)

The following `xml` file represents the highlighting: https://gist.github.com/worldbeater/9f85062caddeceb8cf97719c306546e4

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  2.1.802 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.1.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Ping me if any further details are required.

**Comment by danwalmsley** [comment]
@worldbeater there is not 0.10.0-preview2 of avaloniaedit...

only preview1... should be compatible with preview2 of avalonia however... can you confirm? I wasnt able to reproduce.

**Comment by worldbeater** [comment]
Yeah, sorry for that, used Avalonia `0.10.0-preview2` in conjunction with AvaloniaEdit `0.10.0-preview1`. Going to a repro soon, thanks!

**Comment by worldbeater** [comment]
@danwalmsley uploaded a repro:

https://github.com/worldbeater/AvaloniaEdit.Performance

```sh
# Managed to test this only on Ubuntu 18.04, not sure if the behavior is the same on all platforms.
git clone git@github.com:worldbeater/AvaloniaEdit.Performance.git
cd ./ReactiveApp
dotnet run
```

With `0.9.x` it works just fine, and with `0.10.0-preview2` it behaves as shown below. Scrolling looks like a slideshow.

![ezgif-7-f50fb6c4ac51](https://user-images.githubusercontent.com/6759207/88685933-31440280-d0ff-11ea-9832-33d4846b2ed0.gif)

**Comment by Gillibald** [comment]
I just ran your project and I don't see any performance issues

**Comment by worldbeater** [comment]
Just ran the project on Windows 10 OS, also not seeing any performance issues. 
So the problem seems to apply to Ubuntu 18 only (or, something is wrong with my own Ubuntu).
Pinging folks to help out with checking if the issue exists on other operating systems.

**Comment by Alantoo** [comment]
On MacOS it works smoothly but there are some other issues on window resize. Here is recorded video: https://youtu.be/7Sd66iE8URU

```
dotnet --info

.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.301/

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777
```

**Comment by CreateLab** [comment]
terrible scrolling in Linux (KDE)
delay about 7 sec
![fish](https://user-images.githubusercontent.com/33497292/88692901-49b81b00-d107-11ea-8389-b10f5ca68de9.gif)

**Comment by rstm-sf** [comment]
I wonder how things are after https://github.com/AvaloniaUI/Avalonia/pull/4437 ?

**Comment by Gillibald** [comment]
That issue is unrelated. Totally different text rendering stack.

**Comment by worldbeater** [comment]
Noticing AvaloniaUI overall GUI slowdown on KDE after the upgrade from 0.9.x to 0.10.x. So probably the issue isn't related to `AvaloniaEdit`, and exists due to some changes in AvaloniaUI internals. However, this is only a suggestion, because there seems to be no regression on macOS or Windows, and on Linux I can see visual lags in complex 0.10.x GUIs sometimes, including this `AvaloniaEdit` issue.

**Comment by HendrikMennen** [comment]
Since 0.10 version typing 500 chars in AvaloniaEdit.Demo (with disabled Undo Stack) will cost about 160mb ram that will stay in memory until you restart. This might be responsible for your performance issues.

**Comment by HendrikMennen** [comment]
Should be fixed by https://github.com/AvaloniaUI/AvaloniaEdit/pull/110

**Comment by aelij** [comment]
Possibly fixed by #110? Can someone verify?

**Comment by worldbeater** [comment]
Just checked AvaloniaUI `0.10.999-cibuild0010245-beta` build and the issue still persists. Here is a recording (still a slideshow):

![ezgif-5-ce4071649c71](https://user-images.githubusercontent.com/6759207/92160241-60087380-ee37-11ea-91f8-4163d0369cc9.gif)

**Comment by worldbeater** [comment]
Just discovered via `htop` on Ubuntu KDE that the app in idle state is constantly maxing out the CPU (constantly 99-100%). E.g. I don't have any background operations running, the app is quite a dummy thing and on Windows/OSX it uses like 1-2% CPU or less. I suspect that some heavy operation is causing the described lag spikes. 

![image](https://user-images.githubusercontent.com/6759207/92219868-d347cf00-eea3-11ea-98ad-9af40591874e.png)

**Comment by worldbeater** [comment]
@aelij just verified with `AvaloniaEdit` added as a submodule, and can confirm that https://github.com/AvaloniaUI/AvaloniaEdit/pull/110 really fixes the issue on Linux!
